spring.application.name=Specialization Tools
spring.datasource.url=jdbc:mysql://localhost:3306/special?useSSL=false&serverTimezone=UTC
#Automatically create/update tables on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.username=root
spring.datasource.password=root